[package]
name = "kernel"
version = "0.1.0"
authors = ["James <j.w.tooke@gmail.com>"]
edition = "2018"

# [lib]
# name = "kernel"
# path = "src/lib.rs"
# crate-type = ["staticlib"]

[profile.release]
lto = true

[features]
default = []
bsp_rpi3 = []
bsp_rpi4 = []

[dependencies]